#!/bin/bash

# Windows 11 Fonts Installation Guide for Arch Linux

echo "================================================"
echo "Windows 11 Fonts Installation for Arch Linux"
echo "================================================"
echo ""

echo "Option 1: Install from AUR (Recommended)"
echo "----------------------------------------"
echo ""
echo "Try these packages in order:"
echo ""
echo "1. ttf-ms-win11-auto (automated, if it works):"
echo "   yay -S ttf-ms-win11-auto"
echo ""
echo "2. ttf-ms-fonts (older Windows fonts - already installed):"
echo "   yay -S ttf-ms-fonts"
echo ""
echo "3. ttf-vista-fonts (Vista/7 era fonts):"
echo "   yay -S ttf-vista-fonts"
echo ""

echo "Option 2: Manual Installation (Most Reliable)"
echo "--------------------------------------------"
echo ""
echo "If you have access to a Windows 11 machine:"
echo ""
echo "1. Copy fonts from Windows 11:"
echo "   C:\\Windows\\Fonts\\"
echo ""
echo "2. On Linux, create local fonts directory:"
echo "   mkdir -p ~/.local/share/fonts/WindowsFonts"
echo ""
echo "3. Copy .ttf files to:"
echo "   ~/.local/share/fonts/WindowsFonts/"
echo ""
echo "4. Update font cache:"
echo "   fc-cache -fv"
echo ""

echo "Option 3: Use Wine's Font System"
echo "---------------------------------"
echo ""
echo "Install Wine font replacements:"
echo "   winetricks corefonts"
echo "   winetricks allfonts"
echo ""

echo "Option 4: Install Microsoft TrueType Core Fonts"
echo "-----------------------------------------------"
echo ""
echo "These are the free Microsoft fonts (Arial, Times, etc):"
echo "   yay -S ttf-ms-fonts"
echo "   sudo pacman -S ttf-liberation  # Open source replacements"
echo "   sudo pacman -S ttf-dejavu       # Already installed"
echo ""

echo "================================================"
echo "Current Status Check"
echo "================================================"
echo ""
echo "Installed Microsoft/Windows fonts:"
pacman -Qs ttf-ms
echo ""
echo "Installed Liberation fonts (Arial replacement):"
pacman -Qs liberation
echo ""
echo "Installed DejaVu fonts:"
pacman -Qs dejavu
echo ""

echo "================================================"
echo "Font Cache"
echo "================================================"
echo ""
echo "Rebuild font cache (do this after installing fonts):"
echo "   fc-cache -fv"
echo ""
echo "List all available fonts:"
echo "   fc-list | grep -i arial"
echo "   fc-list | grep -i segoe"
echo ""
